#ifndef SENSOR_STATUS_H
#define SENSOR_STATUS_H

typedef enum {
    SENSOR_STATUS_VALID = 0,
    SENSOR_STATUS_NOT_INITIALIZED,
    SENSOR_STATUS_TIMEOUT,
    SENSOR_STATUS_CHECKSUM_ERROR,
    SENSOR_STATUS_IO_ERROR,
    SENSOR_STATUS_OUT_OF_RANGE,
    SENSOR_STATUS_HEATER_WARMUP,
    SENSOR_STATUS_CALIBRATION_MISSING,
    SENSOR_STATUS_RAW_UNCALIBRATED,
    SENSOR_STATUS_RATE_LIMITED,
    SENSOR_STATUS_NO_NEW_DATA,
    SENSOR_STATUS_UNSUPPORTED
} sensor_status_t;

const char *sensor_status_name(sensor_status_t status);

#endif
